### PR TITLE
Full website

### PR DESCRIPTION
**Pull request by haliljon**
## In this PR I was able to:

> - create full website using react app.
> - use React Router.

### CODE REVIEW

**Review by muneebulrehman — APPROVED** [review]
Hi @haliljon , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- No linter errors
- Descriptive PR
- Good UI

## Optional suggestions

- [ ] I see you have used function declaration at some places for defining your functions. However, since the introduction of arrow functions in ES6, it is a convention to use arrow functions where ever possible. I would strongly recommend using arrow functions throughout your code base.
- [ ] The modulo functionality is not working properly. As you can see from the screenshot when I perform a (10 % 3), it gives me a result of 0.3 which is wrong as the answer should be 1. Kindly fix this error. ⬇️
image

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by haliljon** [comment]
Hi @muneebulrehman,

Thank you for the review. About the "%" button I thought it would be the percentage function, it is not calculating modulo.

**Comment by muneebulrehman** [comment]
> Hi @muneebulrehman,
> 
> Thank you for the review. About the "%" button I thought it would be the percentage function, it is not calculating modulo.

@haliljon, I assure you that it is a modulo and not a percentage.

**Comment by haliljon** [comment]
> 

Ok I will change it.

**Pull request merged**
